### ISSUE TITLE
Return value problem

### ISSUE THREAD

**Issue by Liangchengdeye** [swilly22/redisgraph-py#9]
when i use  pretty_print() method, Only print, no return value,so ,How can i get return value?
And when '，' in value ,redis-cli can return value,but python API can't renturn select back,because "Row has incorrect number of values, (actual) 24!=23 (expected)" it's happend! , So I want to know if ',' are not allowed in data statements. If i use python API.

**Comment by swilly22** [comment]
When executing a query, by calling the `query` function you are given a QueryResult object.
In addition to the pretty_print function this object has, you can get direct access to the underline result-set by accessing the `result_set` property, which is an array of records, Please note that the first record is the header row.

```
result = graph.query("MATCH (n) RETURN n")
result. pretty_print()
for record in result.result_set[1:]:
    print record
```

**Comment by Liangchengdeye** [comment]
ok，I succeeded in solving the problem。
